### ISSUE TITLE
using a DEXSCREENER api

### ISSUE THREAD

**Issue by tommycrpt** [NeurProjects/neur-app#17]
**Is your feature request related to a problem? Please describe.**

why is NEUR using a DEXSCREENER api instead of querying the on chain directly?

If you want to interact with DeFi protocols, using a DexScreener API aint the way.

**Describe the solution you'd like**

I took this request from someones X tweet, seems like good to fix that

**Comment by 0xSpotly** [comment]
Why is Solana’s Official Agent Kit using PumpPortal API to launch tokens instead of interacting directly with PumpFun’s Solana program on-chain? Why is it using Jupiter’s API to swap tokens instead of finding pools to swap on-chain?

And why are you creating this GitHub issue with your browser instead of sending a POST request via your terminal? 
Seems it's good to fix your brain

**Comment by slimeonmyhead** [comment]
At this point in time, it is better to iterate faster and get feedback on features before deciding where to optimize. These APIs are pretty generous in usage limits. They provide the data in easily consumable format that allows more features to be pushed out.

If this project relied on RPC calls for everything, it would hit free tier limits quickly and be prohibitive for some developers to test it out. This project is already pretty expensive for the AI calls, it's best right now to keep the barrier to entry low for new devs.

Even Eliza's solana plugin relies on Birdeye Premium API that costs $60/month.

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via here  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app/) Regards
